# Generated by Django 5.0.7 on 2024-07-31 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='events',
            field=models.ManyToManyField(to='main_app.event'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
